"""empty message

Revision ID: 7f109f236271
Revises: 072ef4ffd15d
Create Date: 2023-09-02 00:01:10.049503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f109f236271'
down_revision = '072ef4ffd15d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peoples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('height', sa.String(length=250), nullable=True),
    sa.Column('mass', sa.String(length=250), nullable=True),
    sa.Column('hair_color', sa.String(length=250), nullable=True),
    sa.Column('skin_color', sa.String(length=250), nullable=True),
    sa.Column('eye_color', sa.String(length=250), nullable=True),
    sa.Column('gender', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('characters')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'peoples', ['people_id'], ['id'])
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_character_id_fkey', 'characters', ['character_id'], ['id'])
        batch_op.drop_column('people_id')

    op.create_table('characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('height', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('mass', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hair_color', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('skin_color', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('eye_color', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name='characters_planet_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='characters_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='characters_pkey')
    )
    op.drop_table('peoples')
    # ### end Alembic commands ###
